### ISSUE TITLE
Brainstorm First Discussion

### ISSUE THREAD

**Issue by nataliehoang91** [AHADATAMT/doraemon-tour#1]
### PURPOSE:
An organization needs to develop a landing page of MINION TOUR EVENTS - which its main business model is hosting those events and selling tickets.

### SUGGESTION ON LAYOUT

* Nav Bar --> https://www.taylorswift.com/
* Slide Show/ VIdeo --> https://demo.mekshq.com/?theme=vlog
* Events --> several banners horizontal grid
* Press News/Gallery -> several banners horizontal grid
* Tickets
* Shop --> https://demo.mekshq.com/?theme=vlog
* Footer About us -> https://www.format.com/magazine/resources/photography/online-portfolio-about-page-step-by-step-guide

**Comment by cloudstar91** [comment]
suggestion layout:

* Nav Bar --> https://www.taylorswift.com/
* Slide Show/ VIdeo --> https://demo.mekshq.com/?theme=vlog
*  Events --> several banners horizontal grid
* Press News/Gallery -> several banners horizontal grid
* Tickets
* Shop --> https://demo.mekshq.com/?theme=vlog
* Footer About us -> https://www.format.com/magazine/resources/photography/online-portfolio-about-page-step-by-step-guide

**Comment by bmthang94** [comment]
* Slide Show/ Video --> https://disneyland.disney.go.com/
*  Events --> Pass/Upcoming, chia cột 7/5
* Press News -->  https://www.taylorswift.com/
* Tickets --> form 
* Shop --> smilar news card
* Footer About us 
* Slide Show/ VIdeo --> https://demo.mekshq.com/?theme=vlog
